INHERIT: mkdocs.yml

plugins:
  - mkdoxy:
      projects:
        api:
          # list real directories separated by spaces
          src-dirs: /home/costeas/hexapic-mpi/source
          full-doc: true
          template-dir: docs/api/templates
          doxy-cfg:
            RECURSIVE: YES
            FILE_PATTERNS: "*.h *.hpp *.c *.cc *.cpp"
            EXCLUDE_PATTERNS: "*/build/* */.venv/*"
            MARKDOWN_SUPPORT: YES
            JAVADOC_AUTOBRIEF: NO
            EXTRACT_ALL: YES
            WARN_IF_UNDOCUMENTED: YES
            HAVE_DOT: NO
            DOT_IMAGE_FORMAT: svg
            ENABLE_PREPROCESSING: NO
            MACRO_EXPANSION: NO
            EXPAND_ONLY_PREDEF: NO
  